services:
  - type: web
    name: ruhi-ji-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OWNER_ID
        sync: false
      - key: PORT
        value: 5000